apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vlfk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-orgunit-factory
  app.kubernetes.io/instance: fint-kontroll-orgunit-factory_vlfk_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: vlfk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "vlfk.no"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "vlfk-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "vlfk-no.kontroll.*"
    target:
      kind: Application
      name: fint-kontroll-orgunit-factory

